[project]
name = "quality-graft"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch==2.9.0",
    "cuequivariance-ops-torch-cu12==0.9.0",
    "cuequivariance-torch==0.9.0",
    "pytorch-lightning==2.5.0",
    "torchmetrics==1.8.2",
    "lightning==2.6.1",
    "hydra-core==1.3.2",
    "omegaconf>=2.3.0",
    "einops==0.8.0",
    "numpy>=1.26,<2.0",
    "scipy==1.13.1",
    "biopython==1.84",
    "tqdm==4.66.4",
    "wandb==0.18.7",
    "dm-tree==0.1.8",
    "einx==0.3.0",
    "fairscale==0.4.13",
    "modelcif==1.2",
    "mashumaro==3.14",
    "pyyaml==6.0.2",
    "scikit-learn==1.6.1",
    "matplotlib==3.10.8",
    "transformers==4.48.3",
    "pytest",
    "ml-collections",
    "graphein==1.7.7",
    "boltz[cuda]",
]

# After `uv sync`, install PyG manually:
# uv pip install torch-geometric==2.7.0 torch-scatter==2.1.2 torch-sparse==0.6.18 torch-cluster==1.6.3 -f https://data.pyg.org/whl/torch-2.9.0+cu130.html

# manually reinstall wandb to wandb==0.25.0 since Boltz installation breaks otherwise
# uv pip install wandb==0.25.0

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
